name: 'Deploy to K8S'
description: 'Setup environment to deploy to k8s with helmfile'
inputs:
  app-id:
    required: true
    description: 'Skills Network Bot App Id'
  app-private-key:
    required: true
    description: "Skills Network Bot Private Key"
  ibm-cloud-api-key:
    required: true
    description: "IBM Cloud Api Key"
  ibm-cloud-region:
    required: false
    default: "us-south"
    description: "IBM Cloud Region"
  cluster-name:
    required: true
    description: "Target IBM Cloud Kubernetes Cluster Name"
  gpg-private-key:
    required: true
    description: "GPG Private Key"
outputs:
  ghec-token:
    description: "Organization-wide github access token"
    value: ${{ steps.skills-network-bot-app.outputs.token }}
runs:
  using: "composite"
  steps:
    - id: skills-network-bot-app
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-private-key }}
    - uses: ibm-skills-network/action-ibmcloud-cli@v1
      with:
        ibm-cloud-api-key: ${{ inputs.ibm-cloud-api-key }}
        ibm-cloud-region: ${{ inputs.ibm-cloud-region }}
        ibm-cloud-cli-plugins: container-service
    - run: |
        ibmcloud ks cluster config --cluster ${{ inputs.cluster-name }}
      shell: bash
    - uses: ibm-skills-network/action-helmfile@main
    - uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ inputs.gpg-private-key }}
