on: 
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      ssh_private_key:
        required: true

jobs:
  mirror:
    name: mirror
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ format('git@github.ibm.com:{0}/{1}.git', 'skills-network-mirror', inputs.repo_name) }}
        ssh_private_key:
          ${{ secrets.ssh_private_key }}
