on: 
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      ssh_private_key:
        required: true

jobs:
  mirror:
    name: mirror
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ format('git@github.ibm.com:{0}/{1}.git', 'skills-network-mirror', inputs.repo_name) }}
        ssh_private_key:
          ${{ secrets.ssh_private_key }}
    - run: |
        export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -l git"
        git config --global user.email "mirror@skills.network"
        git config --global user.name "Skills Network Mirror"
        branch="$(git branch --show-current)"
        echo '{ "settingsInheritedFrom": "whitesource-config/whitesource-config@master" }' > .whitesource
        git add .whitesource
        git commit -m "use GHE .whitesource"
        git push mirror $branch
